### ISSUE TITLE
Dependency issue: pub get fail

### ISSUE THREAD

**Issue by aytunch** [gabrielpatricksouza/image_network#13]
> Resolving dependencies...
> Because webviewimage >=0.0.2 depends on webview_flutter ^3.0.4 and webviewimage <0.0.2 depends on webview_flutter ^2.0.13, every version of webviewimage requires webview_flutter ^2.0.13 or ^3.0.4.
> And because every version of core from path depends on webview_flutter ^4.0.2 and image_network >=2.4.0 depends on webviewimage >=0.0.1 <1.0.0, core from path is incompatible with image_network >=2.4.0.
> So, because boss_web depends on both image_network ^2.5.1 and core from path, version solving failed.
> pub get failed

**Comment by gabrielpatricksouza** [comment]
Try replacing the webview_flutter with https://pub.dev/packages/webviewimage

**Comment by david-fischer** [comment]
Hi @gabrielpatricksouza , I think I ran into the same problem. If I understand correctly, the dependency graph is

	image_network(2.5.2) -> webviewimage (0.0.2) -> webview_flutter (^2.0.13 or ^3.0.4.)

However, I have another package, which would require webview_flutter ^4.0.0..

Is it possible for you to bump your dependencies in the webviewimage package?

```
Because no versions of webviewimage match >0.0.2 <1.0.0 and webviewimage <0.0.2 depends on webview_flutter ^2.0.13, webviewimage <0.0.2-∞ or >0.0.2 <1.0.0 requires webview_flutter ^2.0.13.
And because webviewimage 0.0.2 depends on webview_flutter ^3.0.4, webviewimage <1.0.0 requires webview_flutter ^2.0.13 or ^3.0.4.
And because image_network >=2.4.0 depends on webviewimage >=0.0.1 <1.0.0 and supabase_flutter >=1.7.0 depends on webview_flutter ^4.0.0, image_network >=2.4.0 is incompatible with supabase_flutter >=1.7.0.
```

**Comment by gabrielpatricksouza** [comment]
Bug fixed in version: 2.5.3+1.
Thank you for your comment.

**Comment by nietsmmar** [comment]
@gabrielpatricksouza Sorry, but this is not fixed. You upgraded all dependencies except `webview_flutter`. So this is still a problem.

**Comment by gabrielpatricksouza** [comment]
Sorry, I hadn't uploaded all the changes, access the latest version, v2.5.4
